import type { Metadata } from "next";
import SubPageHeader from "@/components/SubPageHeader";
import Footer from "@/components/Footer";
import LegalDocument, { type LegalContent } from "@/components/LegalDocument";

export const metadata: Metadata = {
  title: `Terms of Service — Ordre.`,
  description: "The terms governing your use of Ordre, the AI fashion curator.",
};

const TERMS: LegalContent = {
  title: `Terms of Service`,
  updated: `17 June 2026`,
  intro: [
    {
      p: `These Terms of Service (the **"Terms”**) form a binding agreement between you and **Ordre** (**“Ordre,” “we,” “us,”** or **“our”**) and govern your access to and use of Ordre — the AI stylist — together with its website, applications, and related services (together, the **“AI Stylist"**). The AI Stylist is a private styling and curation atelier that helps you articulate and develop your personal aesthetic.`,
    },
    {
      p: `Please read these Terms carefully. **By accessing or using the AI Stylist, creating an account, or clicking to accept these Terms, you agree to be bound by them and by our Privacy Policy, which is incorporated here by reference.** If you do not agree, you must not use the AI Stylist.`,
    },
    {
      p: `**These Terms contain a binding arbitration provision and a class-action waiver (Section 17) that affect how disputes are resolved. Please review them carefully.**`,
    },
  ],
  sections: [
    {
      title: `Eligibility`,
      blocks: [
        {
          p: `You must be at least **18 years old**, or the age of legal majority in your jurisdiction, to use the AI Stylist. The AI Stylist is not directed to, and may not be used by, children under 16. By using the AI Stylist you represent and warrant that you meet these requirements, that you have the legal capacity to enter into these Terms, and that you are not barred from using the AI Stylist under any applicable law.`,
        },
        {
          p: `If you use the AI Stylist on behalf of an organization, you represent that you are authorized to bind that organization to these Terms, in which case **"you"** refers to that organization.`,
        },
      ],
    },
    {
      title: `The AI Stylist`,
      blocks: [
        {
          p: `Ordre uses artificial intelligence to interpret the text, images, and documents you share and to generate styling guidance, aesthetic analysis, designer and brand suggestions, and related curation. The AI Stylist is provided for personal, non-commercial use to inform and inspire your own choices.`,
        },
        {
          p: `We may add, change, suspend, or discontinue any part of the AI Stylist at any time, including features, content, and supported file types. We may also impose limits on use — such as message, upload, rate, and storage limits — and may modify or remove these limits at our discretion.`,
        },
      ],
    },
    {
      title: `Accounts & Security`,
      blocks: [
        {
          p: `Some features may require an account. You agree to provide accurate, current, and complete information and to keep it up to date. You are responsible for safeguarding your credentials and for all activity that occurs under your account. You must notify us promptly of any unauthorized use or suspected breach of security.`,
        },
        {
          p: `We may refuse, suspend, or terminate accounts at our discretion, including where we reasonably believe a violation of these Terms has occurred.`,
        },
      ],
    },
    {
      title: `AI-Generated Content & Its Limitations`,
      blocks: [
        {
          p: `**Output is generated by artificial intelligence and is provided for informational and inspirational purposes only.** It may be inaccurate, incomplete, out of date, or unsuited to your circumstances, and it may not reflect current availability, pricing, fit, sizing, or authenticity of any item, designer, or brand.`,
        },
        {
          p: `Given the nature of machine learning, output is probabilistic and may vary between users and sessions. Identical or similar prompts may produce output for other users that is the same as or similar to yours. **You are solely responsible for evaluating the output and for any decision or purchase you make in reliance on it.** Ordre does not provide professional, medical, financial, or legal advice, and the AI Stylist is not a substitute for the judgment of a qualified professional.`,
        },
        {
          p: `As between you and Ordre, and to the extent permitted by law, you may use the output generated for you in connection with your personal aesthetic. You may not represent that AI-generated output is human-created where doing so would be deceptive or unlawful.`,
        },
      ],
    },
    {
      title: `Your Content`,
      blocks: [
        {
          p: `**"Your Content"** means anything you submit to the AI Stylist, including messages, descriptions of your taste, images, photographs, documents, and files. **You retain all ownership rights you already hold in Your Content.** Ordre does not claim ownership of it.`,
        },
        {
          p: `You grant Ordre a worldwide, non-exclusive, royalty-free license to host, store, reproduce, process, transmit, and display Your Content **solely to operate, secure, and improve the AI Stylist and to provide it to you** — including by transmitting Your Content to the third-party AI providers described in Section 8 so that responses can be generated. This license ends when Your Content is deleted, except to the extent it has already been shared with third parties or must be retained to comply with law. We do not sell Your Content.`,
        },
        {
          p: `You represent and warrant that you own or have the necessary rights and permissions to submit Your Content, and that Your Content — and our processing of it as described — does not infringe or violate the rights of any third party (including intellectual-property, privacy, and publicity rights) or any applicable law. **Do not upload images of other people without their consent**, and do not upload content you are not authorized to share.`,
        },
      ],
    },
    {
      title: `Acceptable Use`,
      blocks: [
        { p: "You agree not to, and not to attempt to or permit others to:" },
        {
          list: [
            `Use the AI Stylist in violation of any applicable law, regulation, or third-party right;`,
            `Upload or submit content that is unlawful, infringing, defamatory, harassing, hateful, sexually explicit, depicts minors inappropriately, or that you have no right to share;`,
            `Upload or transmit malware, or any file intended to disrupt, damage, probe, or gain unauthorized access to the AI Stylist or its users;`,
            `Reverse engineer, decompile, scrape, or use automated means to access the AI Stylist except as expressly permitted, or attempt to extract underlying models, prompts, or training data;`,
            `Use the AI Stylist or its output to develop, train, or improve any competing artificial-intelligence model or product;`,
            `Circumvent or interfere with rate limits, security measures, content filters, or usage restrictions;`,
            `Resell, sublicense, or commercially exploit the AI Stylist without our prior written consent;`,
            `Use the AI Stylist to generate content that is deceptive, that impersonates another person, or that is intended to harass, defraud, or mislead;`,
            `Misrepresent your identity or your affiliation with any person or organization.`,
          ],
        },
        {
          p: `We may investigate and take appropriate action against any suspected violation, including removing content, limiting or suspending access, and reporting to law-enforcement authorities.`,
        },
      ],
    },
    {
      title: `Intellectual Property`,
      blocks: [
        {
          p: `The AI Stylist, including its software, design, text, graphics, the Ordre name and swan mark, logos, and all related intellectual property, is owned by Ordre or its licensors and is protected by intellectual-property laws. Except for the rights expressly granted to you in these Terms, we reserve all rights in and to the AI Stylist.`,
        },
        {
          p: `We grant you a limited, personal, non-exclusive, non-transferable, revocable license to access and use the AI Stylist for your own personal, non-commercial use, subject to these Terms. You may not use our trademarks without our prior written permission.`,
        },
      ],
    },
    {
      title: `Third-Party AI Providers & Services`,
      blocks: [
        {
          p: `To deliver the AI Stylist, Ordre relies on third-party providers, including artificial-intelligence model providers (currently **Anthropic**) that process your prompts, images, and documents to generate responses. By using the AI Stylist, **you acknowledge and agree that Your Content will be transmitted to and processed by such providers**, subject to their applicable terms and policies.`,
        },
        {
          p: `These providers may retain data for a limited period for purposes such as operating their services, security, and abuse prevention, as described in our Privacy Policy. Ordre does not control, and is not responsible for, the practices of third-party providers, and Ordre cannot delete data held by a provider on your behalf. The AI Stylist may also link to third-party websites and resources; we are not responsible for their content or practices.`,
        },
      ],
    },
    {
      title: `Fees, Subscriptions & Billing`,
      blocks: [
        {
          p: `Certain features may be offered free of charge, on a waitlist or invitation basis, or as paid plans. Where fees apply, we will disclose pricing, billing frequency, and applicable taxes before you are charged.`,
        },
        {
          p: `Unless stated otherwise: **subscriptions renew automatically** at the then-current price until cancelled; you authorize us and our payment processors to charge your payment method on each renewal; and you may cancel at any time, effective at the end of the current billing period. Except where required by law or expressly stated, **fees are non-refundable**, and partial periods are not refunded. We may change prices on prospective, advance notice. Payments are handled by third-party processors, and your use of payment features may be subject to their terms.`,
        },
      ],
    },
    {
      title: `Feedback`,
      blocks: [
        {
          p: `If you choose to send us feedback, suggestions, or ideas about the AI Stylist, you grant Ordre a perpetual, irrevocable, worldwide, royalty-free license to use and incorporate them for any purpose without any obligation or compensation to you.`,
        },
      ],
    },
    {
      title: `Privacy`,
      blocks: [
        {
          p: `Our collection and use of personal information in connection with the AI Stylist is described in our **Privacy Policy**. By using the AI Stylist, you acknowledge that you have read it and understand how your information is handled, including how it is shared with the AI providers described above.`,
        },
      ],
    },
    {
      title: `Disclaimers`,
      blocks: [
        {
          p: `**The AI Stylist and all output are provided "as is” and “as available," without warranties of any kind, whether express, implied, or statutory.** To the fullest extent permitted by law, Ordre disclaims all warranties, including any implied warranties of merchantability, fitness for a particular purpose, title, accuracy, and non-infringement, and any warranty that the AI Stylist will be uninterrupted, secure, error-free, or that output will be accurate, reliable, or meet your expectations.`,
        },
        {
          p: `Any reliance on the AI Stylist or its output is at your own risk. Some jurisdictions do not allow the exclusion of certain warranties, so some of the above may not apply to you.`,
        },
      ],
    },
    {
      title: `Limitation of Liability`,
      blocks: [
        {
          p: `**To the fullest extent permitted by law, Ordre and its officers, employees, and suppliers will not be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages, or for any loss of profits, revenue, data, goodwill, or other intangible losses**, arising out of or relating to your use of, or inability to use, the AI Stylist or its output, even if advised of the possibility of such damages.`,
        },
        {
          p: `To the fullest extent permitted by law, Ordre’s total aggregate liability for all claims relating to the AI Stylist will not exceed the greater of **(a) the amount you paid to Ordre for the AI Stylist in the twelve months preceding the event giving rise to the claim, or (b) one hundred U.S. dollars (US $100).** Some jurisdictions do not allow certain limitations of liability, so some of the above may not apply to you. Nothing in these Terms limits liability that cannot be limited under applicable law.`,
        },
      ],
    },
    {
      title: `Indemnification`,
      blocks: [
        {
          p: `You agree to indemnify, defend, and hold harmless Ordre and its officers, employees, and suppliers from and against any claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising out of or related to: **(a)** Your Content; **(b)** your use of the AI Stylist; **(c)** your violation of these Terms or any applicable law; or **(d)** your violation of the rights of any third party.`,
        },
      ],
    },
    {
      title: `Suspension & Termination`,
      blocks: [
        {
          p: `You may stop using the AI Stylist at any time and may delete your data as described in our Privacy Policy. We may suspend or terminate your access at any time, with or without notice, if we reasonably believe you have violated these Terms, to protect the AI Stylist or other users, or to comply with law.`,
        },
        {
          p: `Upon termination, the rights granted to you will end. Provisions that by their nature should survive — including ownership, licenses you grant, disclaimers, limitations of liability, indemnification, and dispute resolution — will survive termination.`,
        },
      ],
    },
    {
      title: `Changes to These Terms`,
      blocks: [
        {
          p: `We may update these Terms from time to time. If we make material changes, we will provide reasonable notice, such as by posting the updated Terms with a new "last updated" date or by other appropriate means. **Your continued use of the AI Stylist after the changes take effect constitutes your acceptance of the revised Terms.** If you do not agree, you must stop using the AI Stylist.`,
        },
      ],
    },
    {
      title: `Governing Law & Dispute Resolution`,
      blocks: [
        {
          p: `These Terms are governed by the laws of the **State of [State/Country]**, without regard to its conflict-of-laws rules, except where mandatory consumer-protection laws of your place of residence apply.`,
        },
        {
          sub: `Informal resolution`,
        },
        {
          p: `Before filing a claim, you agree to try to resolve the dispute informally by contacting us, and to allow at least 30 days for the matter to be resolved.`,
        },
        {
          sub: `Binding arbitration & class-action waiver`,
        },
        {
          p: `**To the extent permitted by applicable law, any dispute that cannot be resolved informally will be resolved by final and binding individual arbitration, rather than in court, and you and Ordre waive the right to a jury trial and to participate in any class or representative action.** This provision does not apply where prohibited by law, and you may have the right to opt out of arbitration by notifying us within 30 days of first accepting these Terms. Nothing here prevents either party from seeking relief in small-claims court or from seeking injunctive relief for intellectual-property infringement. **If you reside in the EU, UK, or another jurisdiction where such provisions are unenforceable, this Section does not apply to you, and you retain all rights to bring claims in your local courts.**`,
        },
      ],
    },
    {
      title: `General`,
      blocks: [
        {
          p: `These Terms, together with the Privacy Policy and any terms presented for specific features, are the entire agreement between you and Ordre regarding the AI Stylist. If any provision is held unenforceable, the remaining provisions will remain in effect. Our failure to enforce a provision is not a waiver. You may not assign these Terms without our consent; we may assign them in connection with a merger, acquisition, or sale of assets. We are not liable for any delay or failure caused by events beyond our reasonable control. These Terms do not create any agency, partnership, or joint venture between you and Ordre.`,
        },
      ],
    },
    {
      title: `Contact`,
      blocks: [
        {
          p: `Questions about these Terms may be sent to **contact@ordre.style**.`,
        },
      ],
    },
  ],
};

export default function TermsPage() {
  return (
    <main className="relative min-h-screen flex flex-col">
      <SubPageHeader />
      <div style={{ flex: 1 }}>
        <LegalDocument content={TERMS} />
      </div>
      <Footer />
    </main>
  );
}
